services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
